### ISSUE TITLE
V-viewer downloads images twice.

### ISSUE THREAD

**Issue by chavanchetan121** [mirari/v-viewer#78]
Steps to reproduce.:
1. Pass array of image URLs to the viewer.
2. You can observe in devtools that all images from array get downloaded.
3. then hit next you will see image downloads again.

you can refer https://github.com/chavanchetan121/TestApp this repo. to see or reproduce the issue.

**Comment by mirari** [comment]
I have downloaded and run and can not reproduce it.
Make sure `Network`-`Disable cache` in devtools is **not** checked.

By the way, you can show your codes through these sites:
[https://codepen.io/](https://codepen.io/)
[https://codesandbox.io](https://codesandbox.io)

**Comment by flyingL123** [comment]
I am seeing the same behavior, thought it's probably just due to something I am misunderstanding. @mirari I am looking at an example you created [here](https://codesandbox.io/s/v-viewer-zhezr).  When I click the button to load an image, I see them being loaded by the browser many times:

For example, clicking the button load id 0 results in the browser downloading image 200 and 300 three times each:

<img width="1059" alt="Screen Shot 2019-11-18 at 4 59 30 PM" src="https://user-images.githubusercontent.com/2486712/69097639-f85a7680-0a24-11ea-95b4-2d30e61990ac.png">

Do these requests correspond to 1 - the image shown in the viewer, 2 - the thumbnail shown in the viewer, and 3 - the image defined by this line `<img v-for="src in images" :src="src" :key="src" class="image">`?

If so, I am having trouble understanding the proper way to display an "original" sized image without having to place an `img` tag on the page. Is there a way to do this?  I've looked through the [component example](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue) but am still confused.

In my case, I have multiple groups of images on the page. When someone clicks on a thumbnail in one of the groups, I would like to open up viewer to show the original images for those in the group. However, I am having trouble understanding if I am supposed to create a viewer for each group of images, or have one viewer on the page that displays the images I tell it to. If the answer is one viewer, then how do I provide it the original image urls without writing them to the page?

**Comment by mirari** [comment]
@flyingL123 

The former way(create a viewer for each group of images) is simple and clear.
The example has shown the use of thumbnails:
[Component](https://github.com/mirari/v-viewer/blob/master/example/views/example/ComponentExample.vue)
[Directive](https://github.com/mirari/v-viewer/blob/master/example/views/example/DirectiveExample.vue)


And the latter way is also ok, you need to improve the `viewer` component and `show` method to support thumbnails.
Like this:
[https://codesandbox.io/s/v-viewer-zhezr](https://codesandbox.io/s/v-viewer-zhezr)

**Comment by flyingL123** [comment]
@mirari Thank you so much for the help.

I've noticed in your samples you always assign the images with the array spread operator. For example:

`this.images = [...images];`

I have found that if I don't do that, the viewer will not work if I try to load the same image twice in a row. Meaning, if I click on the image once, it loads. Then if I close the image, and click it again, it will not load. But if I click a different one, it will.

Does this have something to do with Vue's reactivity? The viewer doesn't get `inited` again with the same images unless you use that spreader operator?

**Comment by mirari** [comment]
This is better:
```
    show(images, index = 0) {
      if (this.images === images) {
        this.$viewer.view(index);
        return
      }
      this.images = [...images];
      this.index = index;
    }
```

Try again:
[https://codesandbox.io/s/v-viewer-zhezr](https://codesandbox.io/s/v-viewer-zhezr)
